#env: "pettingzoo"
#env_args: {
#    key: "pistonball_v6",
#    time_limit: 300,  # Episode horizon. SHOULD BE 900
#    render_mode: "rgb_array",  # Options: "human", "rgb_array
#    image_encoder: "ResNet18",  # Options: "ResNet18", "SlimSAM", "CLIP"
#    image_encoder_use_cuda: True,  # Whether to load image-encoder in GPU or not.
#    image_encoder_batch_size: 10,  # How many images to encode in a single pass.
#    partial_observation: False,  # Only for "Emtombed: Cooperative" and "Space Invaders"
#    trainable_cnn: False,  # Specifies whether to return image-observation or the encoded vector-observation
#    kwargs: "",
#    seed: 2024
#}

env: "pressureplate"
env_args: {
    key: "pressureplate-linear-4p-v0",
    time_limit: 500,
    render: True,
    seed: 9296
}



t_max: 100000000
agent: "rnn_rome"
hidden_dim: 64         # Size of hidden state for default rnn agent
learner_log_interval: 2000 # Log training stats every {} timesteps
chunk_size_rnn: 10


use_cuda: True # Use gpu by default unless it isn't available
use_cuda_cnn_modules: True # Use gpu. This is only for the CNN modules. If 'use_cuda' is True, 'use_cuda_cnn_modules' should also be True.




# specific for algorithm
gamma: 0.99            #Same for both cleanRL and Pymarlzoo+
lr: 0.00025            #"""the learning rate of the optimizer"""
lr_critic: 0.00025 #0.00001     #was 0.0001
critic_type: "decentralized_critic"
grad_norm_clip: 0.5 #Stond op 10 # Reduce magnitude of gradients above this L2 norm. Cleanrl uses small 0.5 value. We allow for bigger gradients, because of multiple agent settings.


obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

buffer_size: 32 #IN cleanrl 128 steps and minibatches van 32 steps groot. In PyMarlzooplus is 32 the hoeveelheid EPISODES ipv steps. Dit is ook hetzelfde als batch_size. #batch_size: 32 is DAAROM NIET GEBRUIKT

q_nstep: 5 # 1 corresponds to normal r + gammaV
epochs: 4
eps_clip: 0.2 #called clip_coef in cleanrl. It is the same in cleanrl.
entropy_coef: 0.01 #called ent_coef: float = 0.01. It is same in cleanrl

# I CHANGED THIS TO TRUE. CORRESPONDS probablly TO NORM_ADV IN CLEANRL
standardise_returns: False  #"""Toggles advantages normalization""" #dit was true
standardise_rewards: True # dit was false
standardise_advantages: True #Staat niet in cleanrl/pymarlzooplus. Dit is nu op false gezet voor testing

standardise_intrinsic_expl: True
standardise_intrinsic_infl: True
standardise_intrinsic: True

name: "biem_ns"
use_rnn: True #Beter met True, maar veel langzamer

#-------------------Intrinsic motivation-----------
wm_epochs: 4 #epochs for training world models ensemble
alpha: 0 #0.3
beta: 0 #1

#------------------MOA----------------------------
lr_moa: 0.001
moa_loss_weight: 15

#--------------------------Logging---------------------
save_model: True # Save the models to disk
save_model_interval: 5000000 # Save models after this many timesteps
log_interval: 200000 


n_agents: -1 #Dit boeit volgens mij echt geen reet, maar moet RNNagent hebben blijkbaar.
num_iterations: 0 #will be initialized in python script.